PicarasMVCShop/Controllers/CategoriesController.cs
using System.Linq;
using System.Web.Mvc;
using MoreLinq;
using Picaras.Model;

namespace PicarasMVCShop.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly PicarasModel _db = new PicarasModel();
        // GET: Categories
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowByCategory(int id)
        {
            var products = _db.Products.Where(x => x.CategoryId == id && x.Quantity > 0)
                .DistinctBy(x => x.ProductCode);
            ViewBag.Category = _db.Categories.Find(id)?.Name;
            return PartialView(products);
        }

        public ActionResult ShowBySubcategories(int id)
        {
            var products = _db.Products.Where(x => x.SubcategoryId == id && x.Quantity > 0)
                .GroupBy(x => x.ProductCode)
                .Select(x => x.FirstOrDefault());
            ViewBag.Subcategory = _db.SubCategories.Find(id)?.Name;
            return View(products);
        }
    }
}

PicarasMVCShop/Controllers/ItemController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Picaras.Model;
using Picaras.Model.Entities;
using Picaras.Model.ViewModels;

namespace PicarasMVCShop.Controllers
{

    public class ItemController : Controller
    {
        private readonly PicarasModel _db = new PicarasModel();
        // GET: Item
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetProduct(int id)
        {
            var model = GetById(id);
            var sizes = GetSizes(model.ProductCode);
            var agents = GetAgents();
            var productSize = new ProductSize
            {
                Product = model,
                Sizes = sizes,
                Transports = agents
            };
            return PartialView(productSize);
        }

        private Product GetById(int id)
        {
            return _db.Products.Find(id);
        }

        private IEnumerable<string> GetSizes(int productCode)
        {
            var product = _db.Products.Where(x => x.ProductCode == productCode && x.Quantity > 0);
            return product.Select(x => x.Size);

        }

        private IEnumerable<AgentTransport> GetAgents()
        {
            return _db.AgentTransports;
        }

        public JsonResult GetQuantity(int ProductCode)
        {
            var products = _db.Products.Find(ProductCode).Quantity;
            return Json(products, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetQuantityBySize(int pc, string size)
        {
            var products = _db.Products.FirstOrDefault(x => x.ProductCode == pc && x.Size == size && x.Quantity > 0);
            return Json(new 
            {
                Id = products.ProductId,
                Quantity = products.Quantity
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

PicarasMVCShop/Views/Categories/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CategoriesLayout.cshtml";
}

@Html.Action("ShowByCategory", "Categories")

PicarasMVCShop/Views/Categories/ShowByCategory.cshtml
@model IEnumerable<Picaras.Model.Entities.Product>
@if (Model.Any())
{
    <div class="row" style="margin-bottom:40px;">
        <div class="container">
            <h2 class="text-center horizontal-line">Artículos de @ViewBag.Category</h2>
            @foreach (var item in Model)
            {
                <div class="col-md-4 col-xs-12">
                    <div class="thumbnail">
                        <img src="@item.Picture" alt="@item.Name">
                        <div class="caption">
                            <div class="name-price">
                                <h3>@item.Name</h3>
                                <p>@item.Price€</p>
                            </div>
                            <p>@item.Description</p>
                            @Html.ActionLink("Detalles", "Index", "Item", new { id = @item.ProductId }, new { @class = "btn btn-info btn-details" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}
else
{
    <h2 class="text-center quantity">Uppppsss!!! No hay productos en la categoría: @ViewBag.Category</h2>
}

PicarasMVCShop/Views/Categories/ShowBySubcategories.cshtml
@{
    ViewBag.Title = "ShowBySubcategories";
    Layout = "~/Views/Shared/_CategoriesLayout.cshtml";
}

@model IQueryable<Picaras.Model.Entities.Product>
@if (Model.Any())
{
    <div class="row" style="margin-bottom:40px;">
        <div class="container">
            <h2 class="text-center horizontal-line">Artículos de @ViewBag.Subcategory</h2>
            @foreach (var item in Model)
            {
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <img src="@item.Picture" alt="@item.Name">
                        <div class="caption">
                            <div class="name-price">
                                <h3>@item.Name</h3>
                                <p>@item.Price€</p>
                            </div>
                            <p>@item.Description</p>
                            @Html.ActionLink("Detalles", "Index", "Item", new { id = @item.ProductId }, new { @class = "btn btn-info btn-details" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}
else
{
    <h2 class="text-center quantity">Uppppsss!!! No hay productos en la categoría: @ViewBag.Subcategory</h2>
}