PicarasMVCShop/Controllers/LoginController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Schema;
using Picaras.Model;
using Picaras.Model.Entities;
using Picaras.Model.ViewModels;
using PicarasMVCShop.Helpers;

namespace PicarasMVCShop.Controllers
{
    public class LoginController : Controller
    {
        private readonly PicarasModel _db = new PicarasModel();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoginUser()
        {
            return PartialView();
        }
        [HttpPost]
        public JsonResult LoginPage(string UserName, string Password)
        {
            var getUser = _db.Customers.FirstOrDefault(x => x.UserName == UserName);
            if (getUser == null || getUser.Password != Password) return Json(false);
            Session["user"] = getUser;
            return Json(true);
        }

        public ActionResult LogOut()
        {
            Session.Remove("user");
            Session.Remove("cart");
            return View("~/Views/Home/Index.cshtml");
        }

        public ActionResult UserMenu()
        {
            var user = (Customer)Session["user"];
            var orders = _db.Orders.Where(x => x.CustomerId == user.CustomerId);

            return PartialView(new CustomersOdersViewModel
            {
                Customer = user,
                Orders = orders
            });
        }

        [HttpPost]
        public ActionResult SendEmailToReset(string email)
        {
            var user = _db.Customers.FirstOrDefault(x => x.Email == email);
            if (user == null) return View("~/Views/Login/WrongEmail.cshtml");
            const string subject = "Su usuario y contraseña Pícaras";
            var message =
                $"Su usurio es: {user.UserName} y su password: {user.Password}";
            var toAddress = user.Email;
            const string emailCc = "pedrovillacreces@gmail.com";
            SenderEmails.Sender(subject, message, toAddress, emailCc);
            return View("~/Views/Login/PasswordSent.cshtml");

        }

        public ActionResult RememberPassword()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult EditPersonalData(Customer customer)
        {
            var user = _db.Customers.Find(customer.CustomerId);
            if (user != null)
            {
                user.Name = customer.Name;
                user.LastName = customer.LastName;
                user.Birthday = customer.Birthday;
                user.UserName = customer.UserName;
                user.Email = customer.Email;
                user.Phone = customer.Phone;
                _db.Entry(user).State = EntityState.Modified;
                _db.SaveChanges();
            }
            var orders = _db.Orders.Where(x => x.CustomerId == user.CustomerId); 
            return View("~/Views/Login/UserMenu.cshtml", new CustomersOdersViewModel
            {
             Customer   = user,
             Orders = orders
            });
        }

        [HttpPost]
        public ActionResult EditAddressData(Customer customer)
        {
            var user = _db.Customers.Find(customer.CustomerId);
            if (user != null)
            {
                user.Address = customer.Address;
                user.City = customer.City;
                user.Region = customer.Region;
                user.PostCode = customer.PostCode;
                user.Country = customer.Country;
                _db.Entry(user).State = EntityState.Modified;
                _db.SaveChanges();
            }

            var orders = _db.Orders.Where(x => x.CustomerId == user.CustomerId);
            return View("~/Views/Login/UserMenu.cshtml", new CustomersOdersViewModel
            {
                Customer = user,
                Orders = orders
            });
        }

        [HttpGet]
        public ActionResult ShowDelivery(int id)
        {
           // _db.Configuration.ProxyCreationEnabled = false;
            var orderProducts = _db.OrderProduct.Where(x => x.OrderId == id);
            var returnOrderProducts = new List<OrderProduct>();
            foreach (var item in orderProducts)
            {
                returnOrderProducts.Add(new OrderProduct
                {
                    Quantity = item.Quantity,
                    Product = _db.Products.Find(item.ProductId),
                    Order = _db.Orders.Find(item.OrderId)
                });
            }           
            return PartialView(returnOrderProducts);

        }

        [HttpPost]
        public JsonResult DeleteAccount(int id)
        {
            var customer = _db.Customers.Find(id);
            if (customer != null) _db.Customers.Remove(customer);
            _db.SaveChanges();
            Session.Remove("user");
            return Json(_db.Customers.Find(id) == null ? "ok" : "ko");
        }


    }
}

PicarasMVCShop/Controllers/RegisterController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Picaras.Model;
using Picaras.Model.Entities;
using PicarasMVCShop.Helpers;

namespace PicarasMVCShop.Controllers
{
    /// <summary>
    /// cc
    /// </summary>
    public class RegisterController : Controller
    {
        private readonly PicarasModel _db = new PicarasModel();
        // GET: Register
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddUser()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<ActionResult> Register([Bind(Include = "CustomerId,Name,LastName,Address,Country,PostCode,City,Region,Birthday,Phone,Email,UserName,Password,ConfirmPassword, TermsPrivacity")] Customer customer)
        {
            customer.CodeActive = GeneratedCodeAttribute();
            customer.Active = false;           
            var messege = "El código de activación de la cuenta es el: " + customer.CodeActive;
            SenderEmails.Sender("Código Activación de Pícaras", messege,
                customer.Email, "pedrovillacreces@gmail.com");
            _db.Customers.Add(customer);
            await _db.SaveChangesAsync().ConfigureAwait(false);
            return View("~/Views/Register/ActivateAccount.cshtml", customer);
        }

        [HttpPost]
        public ActionResult ActivateAccount(int customerId, string code)
        {
            var user = _db.Customers.Find(customerId);
            if (user == null || user.CodeActive != code) return View("~/Views/Register/ActivateAccount.cshtml");
            user.Active = true;
            _db.Entry(user).Property("Active").IsModified = true;
            _db.SaveChanges();
            return View("~/Views/Login/Index.cshtml");

        }

        private static string GeneratedCodeAttribute()
        {
            var random = new Random();
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, 10)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }
        [HttpPost]
        public ActionResult ActiveAccount(int userId, string code)
        {
            var user =_db.Customers.Find(userId);
            if (user == null || user.CodeActive != code) return View("~/Views/Register/Index.cshtml");
            user.Active = true;
            return View("~/Views/Home/Index.cshtml");
        }

        [HttpPost]
        public JsonResult DoesUserNameExist(string userName)
        {
            var user = _db.Customers.FirstOrDefault(x => x.UserName == userName);
            return Json(user == null);
        }

        [HttpPost]
        public JsonResult DoesEmailExist(string email)
        {
            var user = _db.Customers.FirstOrDefault(x => x.Email == email);
            return Json(user == null);
        }

   }
}

PicarasMVCShop/Views/Register/ActivateAccount.cshtml
@model Picaras.Model.Entities.Customer

@{   
    Layout = "~/Views/Shared/_RememberLayout.cshtml";
}
@using (Html.BeginForm("ActivateAccount", "Register"))
{
    <div class="container">
        <h2 class="text-center horizontal-line">Activar Cuenta</h2>
    </div>
    <div class="container">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label"><strong>Introduce el código de verificación para activar tu cuenta</strong></label>
                <input type="hidden" name="customerId" value="@Model.CustomerId" />
                <input class="form-control" type="text" name="code" required />
                <input class="btn btn-default" type="submit" value="Envíar código" />
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>
}

PicarasMVCShop/Views/Register/AddUser.cshtml
@model Picaras.Model.Entities.Customer

@using (Html.BeginForm("Register", "Register", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <div class="container">
        <h2 class="text-center horizontal-line">Registro de Usuario</h2>
    </div>
    <div class="form-horizontal margin-container container" style="margin-bottom:40px;">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Region, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Birthday, new { @class = "form-control", type = "date" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2"></label>
            <div class="col-sm-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.TermsPrivacity)
                    <label for="TermsPrivacity">
                        Términos y condiciones de <span data-toggle="modal"
                                                        data-target="#modalPrivacityRegister"
                                                        style="text-decoration: underline; color: blue;">
                            privacidad
                        </span>
                    </label>
                    @Html.ValidationMessageFor(model => model.TermsPrivacity, "", new { @class = "text-danger" })

                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear Usuario" class="btn btn-send" />
                @Html.ActionLink("Volver Inicio", "Index", "Home", null, new { @class = "btn btn-back-contact" })

            </div>
        </div>
    </div>
    <div class="modal fade" id="modalPrivacityRegister" tabindex="-1" role="dialog" aria-labelledby="modalPrivacityRegisterLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="orderModalLabel">Terminos y privacidad</h4>
                </div>
                <div class="" id="">

                </div>
            </div>
        </div>
    </div>
}

PicarasMVCShop/Views/Register/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_RegisterLayout.cshtml";
}

@Html.Action("AddUser", "Register")

PicarasMVCShop/Views/Register/RegisterIcon.cshtml
@using Picaras.Model.Entities
@{
    var isUser = Session["user"];
    var userMap = (Customer)Session["user"];
}
@if (isUser == null)
{
    <div class="login-register">
        <div class="shopping-cart-wrapper">
            <a href="/Register"><i class="fas fa-user-plus"></i> Registrar</a>
        </div>
        <div class="shopping-cart-wrapper">
            <a href="/Login"><i class="fas fa-user"></i> Acceder</a>
        </div>
    </div>
}
else
{
    <div class="shopping-cart-wrapper" style="margin-top: 7px;">
        <div class="dropdown is-hoverable">
            <div class="dropdown-trigger">
                <button class="button" aria-haspopup="true" aria-controls="dropdown-menu4">
                    <span>Bienvenido: @userMap.Name</span>
                    <span class="icon is-small">
                        <i class="fas fa-angle-down" aria-hidden="true"></i>
                    </span>
                </button>
            </div>
            <div class="dropdown-menu" id="dropdown-menu4" role="menu" style="top: 86%;">
                <div class="dropdown-content">
                    <div class="dropdown-item">
                        @Html.ActionLink("Cerrar Sesión", "Logout", "Login")
                        @Html.ActionLink("Menú Usuario", "UserMenu", "Login")
                    </div>
                </div>
            </div>
        </div>
    </div>
}