PicarasMVCShop/Controllers/ContactController.cs
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using PicarasMVCShop.Helpers;

namespace PicarasMVCShop.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SendEmail()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult SendData()
        {
            SenderEmails.Sender(this.Request["Subject"], this.Request["Message"],
                "pedrovillacreces@gmail.com", this.Request["Email"]);
           
            return View();
        }
    }
}

PicarasMVCShop/Controllers/HomeController.cs
using Picaras.Model;
using Picaras.Model.Entities;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MoreLinq;


namespace PicarasMVCShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly PicarasModel _db = new PicarasModel();
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MenuHeader()
        {
            var model = _db.Categories.OrderBy(x => x.Name);
            return PartialView(model);
        }

        public ActionResult Slider()
        {
            var model = GetSlider();
            return PartialView(model);
        }
        public ActionResult BestSeller()
        {
            var model = GetBestSeller();
            return PartialView(model);
        }
        public ActionResult MostRecent()
        {
            var model = GetRecentAdded();
            return PartialView(model);
        }

        private IEnumerable<Category> Getall()
        {
            return _db.Categories.OrderBy(x=>x.Name);
        }

        private List<AdminSlider> GetSlider()
        {
            return _db.AdminSlider.ToList();
        }

        private IEnumerable<Product> GetBestSeller()
        {
            return _db.Products.OrderBy(x => x.NumberOfSales)
                .Take(16).AsEnumerable()
                .DistinctBy(x=>x.ProductCode)
                .Where(x => x.Quantity > 0);
        }

        private IEnumerable<Product> GetRecentAdded()
        {
            return _db.Products.OrderBy(x => x.CreateDateTime)
                .Take(16)
                .AsEnumerable()
                .DistinctBy(x => x.ProductCode)
                .Where(x => x.Quantity > 0);
        }

        public ActionResult Footer()
        {
            var model = Getall();
            return PartialView(model);
        }

    }
}

PicarasMVCShop/Controllers/ItemController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Picaras.Model;
using Picaras.Model.Entities;
using Picaras.Model.ViewModels;

namespace PicarasMVCShop.Controllers
{

    public class ItemController : Controller
    {
        private readonly PicarasModel _db = new PicarasModel();
        // GET: Item
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetProduct(int id)
        {
            var model = GetById(id);
            var sizes = GetSizes(model.ProductCode);
            var agents = GetAgents();
            var productSize = new ProductSize
            {
                Product = model,
                Sizes = sizes,
                Transports = agents
            };
            return PartialView(productSize);
        }

        private Product GetById(int id)
        {
            return _db.Products.Find(id);
        }

        private IEnumerable<string> GetSizes(int productCode)
        {
            var product = _db.Products.Where(x => x.ProductCode == productCode && x.Quantity > 0);
            return product.Select(x => x.Size);

        }

        private IEnumerable<AgentTransport> GetAgents()
        {
            return _db.AgentTransports;
        }

        public JsonResult GetQuantity(int ProductCode)
        {
            var products = _db.Products.Find(ProductCode).Quantity;
            return Json(products, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetQuantityBySize(int pc, string size)
        {
            var products = _db.Products.FirstOrDefault(x => x.ProductCode == pc && x.Size == size && x.Quantity > 0);
            return Json(new 
            {
                Id = products.ProductId,
                Quantity = products.Quantity
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

PicarasMVCShop/Controllers/OutletController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MoreLinq;
using Picaras.Model;
using Picaras.Model.Entities;

namespace PicarasMVCShop.Controllers
{
    public class OutletController : Controller
    {
        private readonly PicarasModel _db = new PicarasModel();
        // GET: Outlet
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Outlets()
        {
            var outletItems = GetOutletItems();
            return PartialView(outletItems);
        }

        private IEnumerable<Product> GetOutletItems()
        {
            return _db.Products.Where(x => x.IsOutlet && x.Quantity > 0)
                .DistinctBy(x => x.ProductCode)
                .OrderBy(x=>x.Price);
        }
    }
}

PicarasMVCShop/Controllers/RegisterController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Picaras.Model;
using Picaras.Model.Entities;
using PicarasMVCShop.Helpers;

namespace PicarasMVCShop.Controllers
{
    /// <summary>
    /// cc
    /// </summary>
    public class RegisterController : Controller
    {
        private readonly PicarasModel _db = new PicarasModel();
        // GET: Register
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddUser()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<ActionResult> Register([Bind(Include = "CustomerId,Name,LastName,Address,Country,PostCode,City,Region,Birthday,Phone,Email,UserName,Password,ConfirmPassword, TermsPrivacity")] Customer customer)
        {
            customer.CodeActive = GeneratedCodeAttribute();
            customer.Active = false;           
            var messege = "El código de activación de la cuenta es el: " + customer.CodeActive;
            SenderEmails.Sender("Código Activación de Pícaras", messege,
                customer.Email, "pedrovillacreces@gmail.com");
            _db.Customers.Add(customer);
            await _db.SaveChangesAsync().ConfigureAwait(false);
            return View("~/Views/Register/ActivateAccount.cshtml", customer);
        }

        [HttpPost]
        public ActionResult ActivateAccount(int customerId, string code)
        {
            var user = _db.Customers.Find(customerId);
            if (user == null || user.CodeActive != code) return View("~/Views/Register/ActivateAccount.cshtml");
            user.Active = true;
            _db.Entry(user).Property("Active").IsModified = true;
            _db.SaveChanges();
            return View("~/Views/Login/Index.cshtml");

        }

        private static string GeneratedCodeAttribute()
        {
            var random = new Random();
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, 10)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }
        [HttpPost]
        public ActionResult ActiveAccount(int userId, string code)
        {
            var user =_db.Customers.Find(userId);
            if (user == null || user.CodeActive != code) return View("~/Views/Register/Index.cshtml");
            user.Active = true;
            return View("~/Views/Home/Index.cshtml");
        }

        [HttpPost]
        public JsonResult DoesUserNameExist(string userName)
        {
            var user = _db.Customers.FirstOrDefault(x => x.UserName == userName);
            return Json(user == null);
        }

        [HttpPost]
        public JsonResult DoesEmailExist(string email)
        {
            var user = _db.Customers.FirstOrDefault(x => x.Email == email);
            return Json(user == null);
        }

   }
}

PicarasMVCShop/Views/Home/BestSeller.cshtml
@using Picaras.Model.Entities
@model IEnumerable<Product>
<div class="container">
    <h4 class="text-center horizontal-line">ARTÍCULOS MÁS VENDIDOS</h4>
    @foreach (var item in Model)
    {
        if (item.Picture == null)
        {
            item.Picture = $"/Content/Images/noImagen.jpg";
        }
        <div class="col-sm-6 col-md-4" style="margin-bottom: 20px;">
            <div class="thumbnail">
                <img src="@item.Picture" alt="@item.Name">
                <div class="caption">
                    <div class="name-price">
                        <h3>@item.Name</h3>
                        <p>@item.Price€</p>
                    </div>
                    <p>@item.Description</p>
                    @Html.ActionLink("Detalles", "Index", "Item", new { id = @item.ProductId }, new { @class = "btn btn-info btn-details" })
                </div>
            </div>
        </div>
    }
</div>

PicarasMVCShop/Views/Home/Footer.cshtml
@using Picaras.Model.Entities
@model IEnumerable<Category>

<div class="container">
    <div class="show-categories col-md-3">
        <h4>Menú Categorías</h4>
        <ul>
            @foreach (var item in Model)
            {
                <li style="list-style-type: none;"><a href="/Categories/Index/@item.CategoryId"><i class="far fa-calendar-check"></i> @item.Name</a></li>
            }
        </ul>
    </div>
    <div class="social-media-footer col-md-3">
        <h4>Redes Sociales</h4>
        <ul style="list-style-type: none;">
            <li><i class="fab fa-facebook-square"></i> Facebook</li>
            <li><i class="fab fa-twitter-square"> </i>Twitter</li>
            <li><i class="fab fa-instagram"></i> Instagram</li>
            <li><i class="fab fa-linkedin"></i> Linkedin</li>
            <li><i class="fab fa-whatsapp-square"></i> Whatsapp</li>
        </ul>
    </div>
    <div class="contact-us social-media-footer col-md-3">
        <h4>Encuéntranos: </h4>
        <ul style="list-style-type: none; padding-left:10px;">
            <li><i class="fas fa-map-marker-alt"></i> Calle dkjhkadkja 45</li>
            <li><i class="fas fa-map-marker-alt"></i> Telefono: 6559999990</li>
            <li><i class="fas fa-map-marker-alt"></i> Correo Electrónico: admin@picaras.es</li>
        </ul>
    </div>
    <div class="payments social-media-footer col-md-3">
        <h4>Tipos de Pago</h4>
        <ul style="list-style-type: none;">
            <li><i class="fab fa-paypal"></i> Paypal</li>
            <li><i class="fas fa-credit-card"></i> Visa</li>
            <li><i class="fas fa-university"></i> Transferencia Bancaria</li>
            <li><i class="fas fa-hand-holding-usd"></i> Pago directo en tienda</li>
        </ul>
    </div>
</div>
<div class="container"><p style="color:white;">&copy; @DateTime.Now.Year - Pícaras Closet, todos los derechos reservados. Web creada por @@PVillacreces</p></div>

PicarasMVCShop/Views/Home/Index.cshtml
@Html.Action("BestSeller", "Home")
@Html.Action("MostRecent", "Home")

PicarasMVCShop/Views/Home/MenuHeader.cshtml
@using Picaras.Model.Entities
@model IEnumerable<Category>
@*@<nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarMenu">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse second-nav" id="navbarMenu">
                <ul class="nav navbar-nav">
                    <li >@Html.ActionLink("INICIO", "Index", "Home")</li>
                    <li >@Html.ActionLink("REGISTRARSE ", "Index", "Register")</li>
                    <li>@Html.ActionLink("CONTACTO", "Index", "Contact")</li>
                    <li>@Html.ActionLink("OUTLET", "Index", "Outlet")</li>
                    @foreach (var item in Model)
                    {
                        <li class="item-nav">
                            <div class="shopping-cart-wrapper">
                                <div class="dropdown is-hoverable">
                                    <div class="dropdown-trigger">
                                        @Html.ActionLink(item.Name.ToUpper(), "Index", "Categories", routeValues: new { id = item.CategoryId }, htmlAttributes: null)
                                    </div>
                                    @if (item.Subcategories.Any())
                                    {
                                        <div class="dropdown-menu" id="dropdown-menu4" role="menu" style="top: 86%;">
                                            <div class="dropdown-content">
                                                <div class="dropdown-item">
                                                    @foreach (var subcategory in item.Subcategories)
                                                    {
                                                        @Html.ActionLink(subcategory.Name.ToUpper(), "ShowBySubcategories", "Categories", routeValues: new { id = subcategory.SubcategoryId }, htmlAttributes: null)
                                                    }
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>*@
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar" style="text-align:center">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("INICIO", "Index", "Home")</li>
                <li>@Html.ActionLink("REGISTRARSE ", "Index", "Register")</li>
                <li>@Html.ActionLink("CONTACTO", "Index", "Contact")</li>
                <li>@Html.ActionLink("OUTLET", "Index", "Outlet")</li>
                @foreach (var item in Model)
                {
                    <li>
                        <div class="dropdown is-hoverable">
                            <div class="dropdown-trigger">
                                @Html.ActionLink(item.Name.ToUpper(), "Index", "Categories", routeValues: new { id = item.CategoryId }, htmlAttributes: null)
                            </div>
                            @if (item.Subcategories.Any())
                            {
                                <div class="dropdown-menu" id="dropdown-menu4" role="menu" style="top: 86%;">
                                    <div class="dropdown-content">
                                        <div class="dropdown-item">
                                            @foreach (var subcategory in item.Subcategories)
                                            {
                                                @Html.ActionLink(subcategory.Name.ToUpper(), "ShowBySubcategories", "Categories", routeValues: new { id = subcategory.SubcategoryId }, htmlAttributes: null)
                                            }
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>

PicarasMVCShop/Views/Home/MostRecent.cshtml
@using Picaras.Model.Entities
@model IEnumerable<Product>
<div class="container" style="margin-bottom:40px;">
    <h4 class="text-center horizontal-line">ARTÍCULOS DE NUEVA TEMPORADA</h4>
    @foreach (var item in Model)
    {
        if (item.Picture == null)
        {
            item.Picture = $"/Content/Images/noImagen.jpg";
        }
        <div class="col-sm-6 col-md-4" style="margin-bottom: 20px;">
            <div class="thumbnail">
                <img src="@item.Picture" alt="@item.Name">
                <div class="caption">
                    <div class="name-price">
                        <h3>@item.Name</h3>
                        <p>@item.Price€</p>
                    </div>
                    <p>@item.Description</p>
                    @Html.ActionLink("Detalles", "Index", "Item", new { id = @item.ProductId }, new { @class = "btn btn-info btn-details" })
                </div>
            </div>
        </div>
    }
</div>
    

PicarasMVCShop/Views/Home/Slider.cshtml
@using Picaras.Model.Entities
@model IEnumerable<AdminSlider>
@{
    var counter = 0;
    var slideActive = "active";
}

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <!-- Wrapper for slides -->
            @foreach (var item in Model)
            {
                if (counter != 0)
                {
                    slideActive = string.Empty;
                }
                <div class="item @slideActive">
                    <img src="@item.Image" alt="@item.Title">
                </div>
                counter++;
            }
        </div>
        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>